motions:
  pickUp:
    - file: ../dataset/dataset_carrybox/pickUp/pickup1.pt
      rsi_skipped_range: []
      weight: 4.0
    - file: ../dataset/dataset_carrybox/pickUp/pickup2.pt
      rsi_skipped_range: []
      weight: 4.0
    - file: ../dataset/dataset_carrybox/pickUp/pickup3.pt
      rsi_skipped_range: []
      weight: 4.0

  putDown:
    - file: ../dataset/dataset_carrybox/putDown/putdown1.pt
      rsi_skipped_range: []
      weight: 5.0
    - file: ../dataset/dataset_carrybox/putDown/putdown2.pt
      rsi_skipped_range: []
      weight: 5.0

  carryWith:
    - file: ../dataset/dataset_carrybox/carryWith/carrywith1.pt
      rsi_skipped_range: []
      weight: 5.0
    - file: ../dataset/dataset_carrybox/carryWith/carrywith2.pt
      rsi_skipped_range: []
      weight: 2.0
    - file: ../dataset/dataset_carrybox/carryWith/carrywith3.pt
      rsi_skipped_range: []
      weight: 5.0

  loco:
    - file: ../dataset/dataset_carrybox/loco_direction/B1_-_stand_to_walk_stageii.pt
      rsi_skipped_range: []
      weight: 1.0
    - file: ../dataset/dataset_carrybox/loco_direction/B2_-_walk_to_stand_stageii.pt
      rsi_skipped_range: []
      weight: 1.0
    - file: ../dataset/dataset_carrybox/loco_direction/B2_-_walk_to_stand_t2_stageii.pt
      rsi_skipped_range: []
      weight: 1.0
    - file: ../dataset/dataset_carrybox/loco_direction/B3_-_walk1_stageii.pt
      rsi_skipped_range: []
      weight: 1.0
    - file: ../dataset/dataset_carrybox/loco_direction/B9_-_walk_turn_left_(90)_stageii.pt
      rsi_skipped_range: []
      weight: 1.0
    - file: ../dataset/dataset_carrybox/loco_direction/B10_-_walk_turn_left_(45)_stageii.pt
      rsi_skipped_range: []
      weight: 1.0
    - file: ../dataset/dataset_carrybox/loco_direction/B11_-_walk_turn_left_(135)_stageii.pt
      rsi_skipped_range: []
      weight: 1.0
    - file: ../dataset/dataset_carrybox/loco_direction/B12_-_walk_turn_right_(90)_stageii.pt
      rsi_skipped_range: []
      weight: 1.0
    - file: ../dataset/dataset_carrybox/loco_direction/B13_-_walk_turn_right_(45)_stageii.pt
      rsi_skipped_range: []
      weight: 1.0
    - file: ../dataset/dataset_carrybox/loco_direction/B14_-_walk_turn_right_(135)_stageii.pt
      rsi_skipped_range: []
      weight: 1.0
    - file: ../dataset/dataset_carrybox/loco_direction/B15_-_walk_turn_around_(same_direction)_stageii.pt
      rsi_skipped_range: []
      weight: 1.0
