motions:
  loco:
    - file: ../dataset/dataset_styleloco/HighKnees_BW.pt
      rsi_skipped_range: []
      weight: 1.0
    - file: ../dataset/dataset_styleloco/HighKnees_FW.pt
      rsi_skipped_range: []
      weight: 1.0
    - file: ../dataset/dataset_styleloco/HighKnees_SW.pt
      rsi_skipped_range: []
      weight: 1.0